ARG baseruntime=sagcr.azurecr.io/esbmsr:11.0

FROM ${baseruntime} 
ARG wpmregistryserver=https://packages.softwareag.com
ARG wpmregistry=softwareag
ARG wpmregistrytoken=
ARG packages=                                             

WORKDIR /opt/softwareag
RUN [ -n "$packages" ] && ./wpm/bin/wpm.sh install ${packages} -jwt_token ${wpmregistrytoken} -ws ${wpmregistryserver} -wpr_registry ${wpmregistry} -target_installation /opt/softwareag/IntegrationServer || echo "No packages provided for installation."