# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WPM_REGISTRY_TOKEN: ${{ secrets.WPM_REGISTRY_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    name: Init and validate outputs
    runs-on: gepe-wsl
    steps:
      - name: Validate
        run: |
          echo "Now validating WPM_REGISTRY_TOKEN"
          if [ -z $WPM_REGISTRY_TOKEN ]; then echo "Validation failed: WPM_REGISTRY_TOKEN is not present as a secret" && exit 1; fi
          echo "Now validating DOCKER_USER"
          if [ -z $DOCKER_USER ]; then echo "Validation failed: DOCKER_USER is not present as a secret" && exit 1; fi
          echo "Now validating DOCKER_PASSWORD"
          if [ -z $DOCKER_PASSWORD ]; then echo "Validation failed: DOCKER_PASSWORD is not present as a secret" && exit 1; fi
          echo "Now validating DOCKER_REGISTRY"
          if [ -z $DOCKER_REGISTRY ]; then echo "Validation failed: DOCKER_REGISTRY is not present as a secret" && exit 1; fi


  # This workflow contains a single job called "build"
  build:
    needs: [init]
    name: Build image
    # The type of runner that the job will run on
    runs-on: gepe-wsl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build the image
        uses: sag-private-cloud/sag-build-image@main
        with:
          context: "."
          dockerfile: Dockerfile_MSR
          image-name: flinttechcontainers.azurecr.io/esbmsr:dev
          wpm-registry: softwareag
          wpm-registry-token: $WPM_REGISTRY_TOKEN
          packages: WmJDBCAdapter:10.3.0

      - name: Push the image to the ACR
        run: |
          echo docker login flinttechcontainers.azurecr.io -u $DOCKER_USER $DOCKER_PASSWORD
          echo docker push 

  deploy:
    needs: [build]
    name: Deploy the solution to the cloud
    runs-on: gepe-wsl

    steps:
      - name: Deploy
        run: echo "deploy the image to the cluster"
