# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    name: Init and validate outputs
    runs-on: gepe-wsl
    steps:
      - name: Validate
        run: echo "validating all inputs"


  # This workflow contains a single job called "build"
  build:
    name: Build image
    # The type of runner that the job will run on
    runs-on: gepe-wsl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build the image
        run: echo "build image"

  deploy:
    name: Deploy the solution to the cloud
    runs-on: gepe-wsl

    steps:
      - name: Deploy
        run: echo "deploy the image to the cluster"
